### ISSUE TITLE
De-compiling DRONE.ENTITY.MBIN and Re-Compiling with no changes causes crash

### ISSUE THREAD

**Issue by theFisher86** [emoose/MBINCompiler#73] opened 2016-09-01 02:32 UTC
I'm guessing this applies to other files as well but I've only noticed it on this one.  If you de-compile `No Man's Sky\GAMEDATA\MODELS\COMMON\ROBOTS\DRONE\ENTITIES\DRONE.ENTITY.MBIN` and then immediately put it back into MBINCompiler and re-compile it back into an MBIN it will cause the game to crash when used.  I've tried it in a separate .pak and by editing an unpacked version of the game itself.

I also tried the same method on `\No Man's Sky\GAMEDATA\MODELS\PLANETS\CREATURES\COWRIG\COW\ENTITIES\_BODY_COW.ENTITY.MBIN` and the game started fine...

**Comment by jvarnes** [comment] 2016-09-01 03:50
Well glad it wasn't just me. I suspect you were trying to do the same thing I was and up the sentinels HP. Crash also occurred for me with the walkers and quads files. Odd that it's just these sentinel entity files... of course I haven't tried every entity file in the data folders so maybe this isn't isolated to those specific files.

PS -
Just curious Fisher but have you tried to hex edit the values as a work a round?

Alternatively I am giving serious consideration to reduce gun and mining damage via the tech table as a means of just reducing player attack power (and thus essentially upping the HP of everything)

**Comment by theFisher86** [comment] 2016-09-01 03:58
I don't do the hex editing stuff... beyond my abilities.  I considered reducing the gun & mining damage as well but it's already fairly low... You might wanna check out what I've been working on so far: [Survival Mode](https://github.com/theFisher86/_mod.SurvivalMode)

**Comment by emoose** [comment] 2016-09-01 10:05
Seems to be a duplicate of #69, I'll close this and let the discussion continue there.

**Closed by emoose** 2016-09-01 10:05 UTC
